"""svg support, region colors

Revision ID: 0175395c9392
Revises: 5ceef971f95d
Create Date: 2020-03-28 12:39:13.761173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0175395c9392'
down_revision = '5ceef971f95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('picture_overlay_color', sa.String(length=7), nullable=True))
    op.add_column('region', sa.Column('style_color', sa.String(length=7), nullable=True))
    op.execute("ALTER TABLE `region` CHANGE `logo` `logo` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `region` CHANGE `picture` `picture` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `category` CHANGE `logo` `logo` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `category` CHANGE `picture` `picture` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `store` CHANGE `logo` `logo` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `store` CHANGE `picture` `picture` ENUM('jpg','png','svg') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'style_color')
    op.drop_column('region', 'picture_overlay_color')
    op.execute("ALTER TABLE `region` CHANGE `logo` `logo` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `region` CHANGE `picture` `picture` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `category` CHANGE `logo` `logo` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `category` CHANGE `picture` `picture` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `store` CHANGE `logo` `logo` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    op.execute("ALTER TABLE `store` CHANGE `picture` `picture` ENUM('jpg','png') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    # ### end Alembic commands ###
