"""category summary

Revision ID: 07cbc917ed4a
Revises: dd101b8ae8f2
Create Date: 2020-03-31 17:04:39.288786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cbc917ed4a'
down_revision = 'dd101b8ae8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('summarize_category', sa.Integer(), nullable=True))
    op.add_column('region', sa.Column('category_style', sa.Enum('summarized', 'detailed'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('region', 'category_style')
    op.drop_column('category', 'summarize_category')
    # ### end Alembic commands ###
