"""extend capabilities

Revision ID: 218e0838dfcf
Revises: 82f16763316a
Create Date: 2020-03-29 08:32:09.885340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '218e0838dfcf'
down_revision = '82f16763316a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_region',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('store', sa.Column('revisited_admin', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'government', 'organisation'), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'region_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'region', ['region_id'], ['id'])
    op.drop_column('user', 'role')
    op.drop_column('store', 'revisited_admin')
    op.drop_table('user_region')
    # ### end Alembic commands ###
