"""slugs and priorities

Revision ID: 552f1ea7d035
Revises: 00f6de819d35
Create Date: 2020-03-24 09:51:59.250148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552f1ea7d035'
down_revision = '00f6de819d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=True)
    op.add_column('region', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_region_slug'), 'region', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_slug'), table_name='region')
    op.drop_column('region', 'slug')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_column('category', 'priority')
    # ### end Alembic commands ###
