"""revisited_organisation

Revision ID: 6e38ed5072fd
Revises: 07cbc917ed4a
Create Date: 2020-04-01 05:38:11.450906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e38ed5072fd'
down_revision = '07cbc917ed4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('revisited_organisation', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'revisited_organisation')
    # ### end Alembic commands ###
