"""deleted field

Revision ID: 77dbf59d2a08
Revises: d15d7d5dc049
Create Date: 2020-03-27 10:25:09.284074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dbf59d2a08'
down_revision = 'd15d7d5dc049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('deleted', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'deleted')
    # ### end Alembic commands ###
