"""more store fields

Revision ID: 82f16763316a
Revises: 0175395c9392
Create Date: 2020-03-29 06:35:27.141773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f16763316a'
down_revision = '0175395c9392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('cuisine', sa.Text(), nullable=True))
    op.add_column('store', sa.Column('diet', sa.Text(), nullable=True))
    op.add_column('store', sa.Column('fair_trade', sa.Enum('yes', 'no', 'only'), nullable=True))
    op.add_column('store', sa.Column('organic', sa.Enum('yes', 'no', 'only'), nullable=True))
    op.add_column('store', sa.Column('origin', sa.Text(), nullable=True))
    op.add_column('store', sa.Column('payment', sa.Text(), nullable=True))
    op.add_column('store', sa.Column('zero_waste', sa.Enum('yes', 'no', 'only'), nullable=True))
    op.execute("ALTER TABLE `store` CHANGE `wheelchair` `wheelchair` ENUM('yes', 'limited', 'no', 'designated') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'zero_waste')
    op.drop_column('store', 'payment')
    op.drop_column('store', 'origin')
    op.drop_column('store', 'organic')
    op.drop_column('store', 'fair_trade')
    op.drop_column('store', 'diet')
    op.drop_column('store', 'cuisine')
    # ### end Alembic commands ###
