"""abstract object dump

Revision ID: ab6e67d61f2f
Revises: 552f1ea7d035
Create Date: 2020-03-27 08:57:33.678600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab6e67d61f2f'
down_revision = '552f1ea7d035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_dump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('suggestion', 'revision'), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_collate='utf8_unicode_ci'
    )
    op.create_index(op.f('ix_object_dump_object'), 'object_dump', ['object'], unique=False)
    op.create_index(op.f('ix_object_dump_type'), 'object_dump', ['type'], unique=False)
    op.drop_index('ix_object_history_type', table_name='object_history')
    op.drop_table('object_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_history',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('modified', mysql.DATETIME(), nullable=False),
    sa.Column('object_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8_unicode_ci', length=255), nullable=True),
    sa.Column('data', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_object_history_type', 'object_history', ['type'], unique=False)
    op.drop_index(op.f('ix_object_dump_type'), table_name='object_dump')
    op.drop_index(op.f('ix_object_dump_object'), table_name='object_dump')
    op.drop_table('object_dump')
    # ### end Alembic commands ###
