"""better selectable object revisions

Revision ID: cdad92104ad0
Revises: 77dbf59d2a08
Create Date: 2020-03-27 14:22:55.870094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdad92104ad0'
down_revision = '77dbf59d2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_dump', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('object_dump', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('object_dump', sa.Column('settled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_dump', 'settled')
    op.drop_column('object_dump', 'region_id')
    op.drop_column('object_dump', 'deleted')
    # ### end Alembic commands ###
