"""source fields

Revision ID: d15d7d5dc049
Revises: ab6e67d61f2f
Create Date: 2020-03-27 09:53:39.976725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15d7d5dc049'
down_revision = 'ab6e67d61f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('source_text', sa.String(length=255), nullable=True))
    op.add_column('store', sa.Column('source_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'source_url')
    op.drop_column('store', 'source_text')
    # ### end Alembic commands ###
